baseURL = "https://cloud-architecture.io/"
theme = "air"
title = "cloud-architecture.io"
sectionPagesMenu = "main"
pygmentsCodeFences = "true"

[author]
  name = "Mike"

[params]
  description = "Architecting for Cloud"
  cover = "images/user.jpg"
  author = "Mike"
  authorlocation = ""
  authorwebsite = "https://soft-practice.com"
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  githubName = "macmike"
  twitterName = "mikemacd"
  hideHUGOSupport = false 
  gitbase = "https://github.com/macmike/cloud-architecture.io/tree/master/content/"

